#!/bin/bash

# Focus tab matching regex

__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

error() {
    echo "$1" 1>&2
    exit 1
}

result=$(chrome-cli list tabs | grep $@)

[ $? -eq 0 ] || error "No match"

$__dir/chrome-focus-tab <<<$result
